//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_de_Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public int numero_cita { get; set; }
        public string cliente { get; set; }
        public int modelo { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombre_evento { get; set; }
        public Nullable<int> valor_dia_modelo { get; set; }
    
        public virtual modelo modelo1 { get; set; }
    }
}
