//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_de_Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        public modelo()
        {
            this.cita = new HashSet<cita>();
        }
    
        public int codigo_unico { get; set; }
        public string nombre { get; set; }
        public string apellido_paterno { get; set; }
        public string apellido_materno { get; set; }
        public string sexo { get; set; }
        public string color_ojos { get; set; }
        public string tez { get; set; }
        public string medidas_anatomicas { get; set; }
        public string observaciones { get; set; }
        public string foto { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public Nullable<byte> estaActivo { get; set; }
    
        public virtual ICollection<cita> cita { get; set; }
    }
}
