//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca_de_Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string userName { get; set; }
        public string password { get; set; }
        public int tipoUsuario { get; set; }
    
        public virtual tipoUsuario tipoUsuario1 { get; set; }
    }
}
